project_id = "vpbdcqzlvwtkumbtnxhe"

[functions.initialize-paystack-payment]
verify_jwt = true

[functions.verify-paystack-payment]
verify_jwt = true

[functions.get-paystack-public-key]
verify_jwt = false
