project_id = "utfvbtcszzafuoyytlpf"

[functions.claim-promo]
verify_jwt = true

[functions.initialize-paystack-payment]
verify_jwt = true

[functions.verify-paystack-payment]
verify_jwt = true

[functions.get-paystack-public-key]
verify_jwt = false

[functions.test-public-key]
verify_jwt = false

[functions.get-paystack-public-key-simple]
verify_jwt = false